swagger: "2.0"
info:
  version: "1.0.0"
  title: API de transactions
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
- http
paths:
  /transactions:
    get:
      summary: Récupérer toutes les transactions du mois en cours
      responses:
        “200”:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        “400”:
          description: Requête invalide
        “404”:
          description: Transactions non trouvées
        “500”:
          description: Erreur interne du serveur
  /transactions/{transaction_id}:
    get:
      summary: Récupérer les détails d'une transaction spécifique
      parameters:
        - name: transaction_id
          in: path
          required: true
          description: ID de la transaction à récupérer
          type: integer
      responses:
        “200”:
          description: OK
          schema:
            $ref: "#/definitions/Transaction"
        “400”:
          description: Requête invalide
        “404”:
          description: Transaction non trouvée
        “500”:
          description: Erreur interne du serveur
  /transactions/{transaction_id}/add-info:
    post:
      summary: Ajouter des informations sur une transaction existante
      parameters:
        - name: transaction_id
          in: path
          required: true
          description: ID de la transaction à modifier
          type: integer
        - name: informations
          in: body
          required: true
          description: Informations à ajouter à la transaction
          schema:
            $ref: "#/definitions/TransactionInput"
      responses:
        “200”:
          description: OK
          schema:
            $ref: "#/definitions/Transaction"
          “400”:
            description: Requête invalide
          “404”:
            description: Transaction non trouvée
          “500”:
            description: Erreur interne du serveur
  /transactions/{transaction_id}/update-info:
    put:
      summary: Modifier les informations d'une transaction existante
      parameters:
        - name: transaction_id
          in: path
          required: true
          description: ID de la transaction à modifier
          type: integer
        - name: informations
          in: body
          required: true
          description: Informations mises à jour pour la transaction
          schema:
            $ref: "#/definitions/TransactionInput"
      responses:
        “200”:
          description: OK
          schema:
            $ref: "#/definitions/Transaction"
        “400”:
          description: Requête invalide
        “404”:
          description: Transaction non trouvée
        “500”:
          description: Erreur interne du serveur
  /transactions/{transaction_id}/delete-info:
    delete:
      summary: Supprimer des informations sur une transaction existante
      parameters:
        - name: transaction_id
          in: path
          required: true
          description: ID de la transaction à modifier
          type: integer
        - name: informations
          in: body
          required: true
          description: Informations à supprimer de la transaction
          schema:
            $ref: "#/definitions/TransactionInput"
      responses:
        “204”:
          description: Supprimé avec succès
        “404”:
          description: Transaction non trouvée
        “500”:
      description: Erreur interne du serveur
  definitions:
    Transaction:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
          format: date-time
        montant:
          type: number
        description:
          type: string
    TransactionInput:
      type: object
      properties:
        date:
          type: string
          format: date-time
        montant:
          type: object

